site_name: Autonomous Car Documentation
site_url: https://hajorda.github.io/rc_documentation/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate  # Allows you to add (+) icons to code lines for explanation
    - announce.dismiss
    - content.code.copy
    - navigation.tabs
# The Social Card Setup
  cards: true
  cards_directory: overrides/cards

plugins:
  - search
  - multirepo:
      # This helps prevent the 'Loop closed' error on some systems
      cleanup: true 
      repos:
        - section: Controller
          import_url: 'https://github.com/Tedu-Autonomous-RC-Car/teleopt_controller?branch=main'
        # - section: Vision
        #   import_url: 'https://github.com/Tedu-Autonomous-RC-Car/vision?branch=main'
        - section: Jetson
          import_url: 'https://github.com/Tedu-Autonomous-RC-Car/jetson?branch=main'

markdown_extensions:
  - admonition                # For !!! note, !!! warning blocks
  - pymdownx.details          # For collapsible sections (great for FAQs)
  - pymdownx.superfences:     # For Mermaid diagrams
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:          # To switch between ROS2 Humble/Foxy or Python/C++
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
