site_name: Autonomous Car Documentation
site_url: https://tedu-autonomous-rc-car.github.io/rc_documentation/
site_description: Project at TED University focusing on autonomous RC racing using Reinforcement Learning (SAC/PPO), Jetson Orin Nano, and ROS2.
site_author: Hajorda
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate  # Allows you to add (+) icons to code lines for explanation
    - announce.dismiss
    - content.code.copy
    - navigation.tabs
# The Social Card Setup
  cards: true
  cards_directory: overrides/cards

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Tedu-Autonomous-RC-Car
    - icon: fontawesome/solid/globe
      link: https://www.tedutas.org/
      name: TEDU Autonomous Systems Lab

plugins:
  - search
  - social
  # - multirepo:
  #     # This helps prevent the 'Loop closed' error on some systems
  #     cleanup: true 
  #     repos:
  #       - section: Controller
  #         import_url: 'https://github.com/Tedu-Autonomous-RC-Car/teleopt_controller?branch=main'
  #       # - section: Vision
  #       #   import_url: 'https://github.com/Tedu-Autonomous-RC-Car/vision?branch=main'
  #       - section: Jetson
  #         import_url: 'https://github.com/Tedu-Autonomous-RC-Car/jetson?branch=main'
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - admonition                # For !!! note, !!! warning blocks
  - pymdownx.details          # For collapsible sections (great for FAQs)
  - pymdownx.superfences:     # For Mermaid diagrams
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:          # To switch between ROS2 Humble/Foxy or Python/C++
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started: setup.md
  - Hardware:
      - Overview: hardware/hardware.md
      - Sensors: hardware/sensors.md
      - Power Management: hardware/power_management.md
      - Chassis & Mechanical: hardware/chassis_mechanical.md
      - Status Board: hardware/status_board.md
      - Bill of Materials: hardware/bom.md
  - Jetson:
      - Teleop Listener Node: jetson/teleop-node.md
      - GPIO Configuration: jetson/gpio-config.md
      - RPLIDAR Setup: jetson/rplidar.md
  - Software:
      - RC Car Model Training: software/model_training.md
      - Model Performance Comparison: software/model_comparison.md
      - 3D Construction: software/3d_construction.md
