name: Deploy Documentation
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build and Deploy
        env:
          # Ensure this secret matches the name you gave it in GitHub Settings
          GithubAccessToken: ${{ secrets.GH_TOKEN_MULTIREPO }}
        run: |
          mkdocs gh-deploy --force