name: Deploy Documentation
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install System Graphics Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build and Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_MULTIREPO }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # This line fixes the 'could not read Username' error for private repos
          git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
          
          mkdocs gh-deploy --force